# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
#FROM gcr.io/distroless/static:latest
## use base:debug for shell access
FROM gcr.io/distroless/static:latest
WORKDIR /
COPY relay.upx relay
ENTRYPOINT ["/relay"]
