FROM golang:1.17 as build
LABEL description="Build container"

ENV CGO_ENABLED 0
COPY . /build
WORKDIR /build
RUN go build -o paralus-init scripts/initialize/main.go

FROM alpine:latest as runtime
LABEL description="Run container"

WORKDIR /usr/bin
COPY --from=build /build/paralus-init /usr/bin/paralus-init
COPY --from=build /build/scripts/initialize/ /usr/bin/scripts/initialize/
ENTRYPOINT ["./paralus-init"]
