syntax = "proto3";
package paralus.dev.types.audit.v1;
option go_package = "github.com/paralus/paralus/proto/types/audit;auditv1";

message AuditResponse {
    Aggregations aggregations = 1;
    Hits hits = 2;
}

message Aggregations {
    AggregatorGroup group_by_type = 1;
    AggregatorGroup group_by_username = 2;
    AggregatorGroup group_by_cluster = 3;
    AggregatorGroup group_by_kind = 4;
    AggregatorGroup group_by_method = 5;
    AggregatorGroup group_by_namespace = 6;
    AggregatorGroup group_by_project = 7;
}

message AggregatorGroup {
    repeated GroupByType buckets = 1;
}

message GroupByType {
    int32 doc_count = 1;
    string key = 2;
}

message DataSourceJSON {
    Data json = 1;
}

message DataSource {
    DataSourceJSON _source = 1;
}

message Hits {
    repeated DataSource hits = 1;    
}

message Data {
    Actor actor = 1;
    string category = 2;
    Client client = 3;
    Detail detail = 4;
    string origin = 5;
    string portal = 6;
    string project = 7;
    string timestamp = 8;
    string type = 9;
    string version = 10;

    string api_version = 11;
    string cluster_name = 12;
    double duration = 13;
    string id = 14;
    string kind = 15;
    string method = 16;
    string name = 17;
    string namespace = 18;
    string organization_id = 19;
    string partner_id = 20;
    string query = 21;
    string remote_addr = 22;
    int32 status_code = 23;
    string session_type = 24;
    string ts = 25;
    string username = 26;
    string url = 27;
    int32 written = 28;
}

message Actor {
    Account account = 1;
    repeated string groups = 2;
    string type = 3;
}

message Account {
    string username = 1;
}

message Client {
    string host = 1;
    string ip = 2;
    string type = 3;
    string user_agent = 4;
}

message Detail {
    string message = 1;
    DetailMeta meta = 2;
}

message DetailMeta {
    string cluster_name = 1;
}