// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TypesconfigPlacementLabel typesconfig placement label
//
// swagger:model typesconfigPlacementLabel
type TypesconfigPlacementLabel struct {

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this typesconfig placement label
func (m *TypesconfigPlacementLabel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this typesconfig placement label based on context it is used
func (m *TypesconfigPlacementLabel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TypesconfigPlacementLabel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TypesconfigPlacementLabel) UnmarshalBinary(b []byte) error {
	var res TypesconfigPlacementLabel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
