:host = http://localhost:11000
:partner = 439fd1c6-e947-4dad-a9e9-ca1f50898f85
:org = 960bb196-76b2-430a-a72e-88d8362c07c3
:userid = 8f35abd7-0c8c-4770-a2c7-430f79bb5eb7

## Users

# Create user
POST :host/auth/v3/partner/:partner/organization/:org/users
{"spec": {"username": "anothernewguy@notaprovider.com", "firstName": "John", "lastName": "Doe"}}
-> jq-set-var :userid .metadata.id

# Get all users
GET :host/auth/v3/partner/:partner/organization/:org/users

# Get single user
GET :host/auth/v3/partner/:partner/organization/:org/user/:userid

# Update user info
PUT :host/auth/v3/partner/:partner/organization/:org/user/:userid
{"spec": {"username": "changedemail@notaprovider.com", "firstName": "John", "lastName": "Doe"}}

# Delete single user
DELETE :host/auth/v3/partner/:partner/organization/:org/user/:userid


## Groups

# Create group

POST :host/auth/v3/partner/:partner/organization/:org/groups
Content-Type: application/yaml

metadata:
  name: my-group
  description: My first description
  partner: :partner
  organization: :org
spec:
  type: simple

# Get all groups
GET :host/auth/v3/partner/:partner/organization/:org/groups