// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto/rpc/sentry/kubectl_cluster.proto

/*
Package sentry is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package sentry

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_KubectlClusterSettings_UpdateKubectlClusterSettings_0(ctx context.Context, marshaler runtime.Marshaler, client KubectlClusterSettingsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateKubectlClusterSettingsRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["opts.urlScope"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "opts.urlScope")
	}

	err = runtime.PopulateFieldFromPath(&protoReq, "opts.urlScope", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "opts.urlScope", err)
	}

	msg, err := client.UpdateKubectlClusterSettings(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_KubectlClusterSettings_UpdateKubectlClusterSettings_0(ctx context.Context, marshaler runtime.Marshaler, server KubectlClusterSettingsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateKubectlClusterSettingsRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["opts.urlScope"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "opts.urlScope")
	}

	err = runtime.PopulateFieldFromPath(&protoReq, "opts.urlScope", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "opts.urlScope", err)
	}

	msg, err := server.UpdateKubectlClusterSettings(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_KubectlClusterSettings_GetKubectlClusterSettings_0 = &utilities.DoubleArray{Encoding: map[string]int{"opts": 0, "urlScope": 1}, Base: []int{1, 1, 1, 0}, Check: []int{0, 1, 2, 3}}
)

func request_KubectlClusterSettings_GetKubectlClusterSettings_0(ctx context.Context, marshaler runtime.Marshaler, client KubectlClusterSettingsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetKubectlClusterSettingsRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["opts.urlScope"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "opts.urlScope")
	}

	err = runtime.PopulateFieldFromPath(&protoReq, "opts.urlScope", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "opts.urlScope", err)
	}

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_KubectlClusterSettings_GetKubectlClusterSettings_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetKubectlClusterSettings(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_KubectlClusterSettings_GetKubectlClusterSettings_0(ctx context.Context, marshaler runtime.Marshaler, server KubectlClusterSettingsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetKubectlClusterSettingsRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["opts.urlScope"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "opts.urlScope")
	}

	err = runtime.PopulateFieldFromPath(&protoReq, "opts.urlScope", val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "opts.urlScope", err)
	}

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_KubectlClusterSettings_GetKubectlClusterSettings_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetKubectlClusterSettings(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterKubectlClusterSettingsHandlerServer registers the http handlers for service KubectlClusterSettings to "mux".
// UnaryRPC     :call KubectlClusterSettingsServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterKubectlClusterSettingsHandlerFromEndpoint instead.
func RegisterKubectlClusterSettingsHandlerServer(ctx context.Context, mux *runtime.ServeMux, server KubectlClusterSettingsServer) error {

	mux.Handle("PUT", pattern_KubectlClusterSettings_UpdateKubectlClusterSettings_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/rafay.dev.sentry.rpc.KubectlClusterSettings/UpdateKubectlClusterSettings", runtime.WithHTTPPathPattern("/v2/sentry/kubectl/{opts.urlScope=cluster/*}/settings"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_KubectlClusterSettings_UpdateKubectlClusterSettings_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_KubectlClusterSettings_UpdateKubectlClusterSettings_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_KubectlClusterSettings_GetKubectlClusterSettings_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/rafay.dev.sentry.rpc.KubectlClusterSettings/GetKubectlClusterSettings", runtime.WithHTTPPathPattern("/v2/sentry/kubectl/{opts.urlScope=cluster/*}/settings"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_KubectlClusterSettings_GetKubectlClusterSettings_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_KubectlClusterSettings_GetKubectlClusterSettings_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterKubectlClusterSettingsHandlerFromEndpoint is same as RegisterKubectlClusterSettingsHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterKubectlClusterSettingsHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterKubectlClusterSettingsHandler(ctx, mux, conn)
}

// RegisterKubectlClusterSettingsHandler registers the http handlers for service KubectlClusterSettings to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterKubectlClusterSettingsHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterKubectlClusterSettingsHandlerClient(ctx, mux, NewKubectlClusterSettingsClient(conn))
}

// RegisterKubectlClusterSettingsHandlerClient registers the http handlers for service KubectlClusterSettings
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "KubectlClusterSettingsClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "KubectlClusterSettingsClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "KubectlClusterSettingsClient" to call the correct interceptors.
func RegisterKubectlClusterSettingsHandlerClient(ctx context.Context, mux *runtime.ServeMux, client KubectlClusterSettingsClient) error {

	mux.Handle("PUT", pattern_KubectlClusterSettings_UpdateKubectlClusterSettings_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/rafay.dev.sentry.rpc.KubectlClusterSettings/UpdateKubectlClusterSettings", runtime.WithHTTPPathPattern("/v2/sentry/kubectl/{opts.urlScope=cluster/*}/settings"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_KubectlClusterSettings_UpdateKubectlClusterSettings_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_KubectlClusterSettings_UpdateKubectlClusterSettings_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_KubectlClusterSettings_GetKubectlClusterSettings_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/rafay.dev.sentry.rpc.KubectlClusterSettings/GetKubectlClusterSettings", runtime.WithHTTPPathPattern("/v2/sentry/kubectl/{opts.urlScope=cluster/*}/settings"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_KubectlClusterSettings_GetKubectlClusterSettings_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_KubectlClusterSettings_GetKubectlClusterSettings_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_KubectlClusterSettings_UpdateKubectlClusterSettings_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 1, 0, 4, 2, 5, 4, 2, 5}, []string{"v2", "sentry", "kubectl", "cluster", "opts.urlScope", "settings"}, ""))

	pattern_KubectlClusterSettings_GetKubectlClusterSettings_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 1, 0, 4, 2, 5, 4, 2, 5}, []string{"v2", "sentry", "kubectl", "cluster", "opts.urlScope", "settings"}, ""))
)

var (
	forward_KubectlClusterSettings_UpdateKubectlClusterSettings_0 = runtime.ForwardResponseMessage

	forward_KubectlClusterSettings_GetKubectlClusterSettings_0 = runtime.ForwardResponseMessage
)
