// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RPCRegisterClusterRequest rpc register cluster request
//
// swagger:model rpcRegisterClusterRequest
type RPCRegisterClusterRequest struct {

	// signing request
	// Format: byte
	SigningRequest strfmt.Base64 `json:"signingRequest,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this rpc register cluster request
func (m *RPCRegisterClusterRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rpc register cluster request based on context it is used
func (m *RPCRegisterClusterRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RPCRegisterClusterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RPCRegisterClusterRequest) UnmarshalBinary(b []byte) error {
	var res RPCRegisterClusterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
