// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ProxyConfig v3 proxy config
//
// swagger:model v3ProxyConfig
type V3ProxyConfig struct {

	// AllowInsecureBootstrap
	//
	// Allow insecure bootstrap
	AllowInsecureBootstrap bool `json:"allowInsecureBootstrap,omitempty"`

	// BootstrapCA
	//
	// Certificate Authority of bootstrap server
	BootstrapCA string `json:"bootstrapCA,omitempty"`

	// Enabled
	//
	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// HttpProxy
	//
	// http proxy
	HTTPProxy string `json:"httpProxy,omitempty"`

	// HttpsProxy
	//
	// https proxy
	HTTPSProxy string `json:"httpsProxy,omitempty"`

	// noproxy
	//
	// noproxy
	NoProxy string `json:"noProxy,omitempty"`

	// ProxyAuth
	//
	// proxy auth
	ProxyAuth string `json:"proxyAuth,omitempty"`
}

// Validate validates this v3 proxy config
func (m *V3ProxyConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v3 proxy config based on context it is used
func (m *V3ProxyConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3ProxyConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ProxyConfig) UnmarshalBinary(b []byte) error {
	var res V3ProxyConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
