// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Corev1ResourceRequirements ResourceRequirements describes the compute resource requirements.
//
// swagger:model corev1ResourceRequirements
type Corev1ResourceRequirements struct {

	// Limits describes the maximum amount of compute resources allowed.
	// More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
	// +optional
	Limits map[string]ResourceQuantity `json:"limits,omitempty"`

	// Requests describes the minimum amount of compute resources required.
	// If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
	// otherwise to an implementation-defined value.
	// More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
	// +optional
	Requests map[string]ResourceQuantity `json:"requests,omitempty"`
}

// Validate validates this corev1 resource requirements
func (m *Corev1ResourceRequirements) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLimits(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequests(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Corev1ResourceRequirements) validateLimits(formats strfmt.Registry) error {
	if swag.IsZero(m.Limits) { // not required
		return nil
	}

	for k := range m.Limits {

		if err := validate.Required("limits"+"."+k, "body", m.Limits[k]); err != nil {
			return err
		}
		if val, ok := m.Limits[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("limits" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("limits" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *Corev1ResourceRequirements) validateRequests(formats strfmt.Registry) error {
	if swag.IsZero(m.Requests) { // not required
		return nil
	}

	for k := range m.Requests {

		if err := validate.Required("requests"+"."+k, "body", m.Requests[k]); err != nil {
			return err
		}
		if val, ok := m.Requests[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requests" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requests" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this corev1 resource requirements based on the context it is used
func (m *Corev1ResourceRequirements) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLimits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRequests(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Corev1ResourceRequirements) contextValidateLimits(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Limits {

		if val, ok := m.Limits[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *Corev1ResourceRequirements) contextValidateRequests(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Requests {

		if val, ok := m.Requests[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Corev1ResourceRequirements) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Corev1ResourceRequirements) UnmarshalBinary(b []byte) error {
	var res Corev1ResourceRequirements
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
